### ISSUE TITLE
CSS improvement for hidden secondary_info

### ISSUE THREAD

**Issue by ThomDietrich** [artem-sedykh/mini-climate-card#100]
Hey guys.
I'm, using the new option to hide the secondary_info, introduced in #95.

```yaml
  - type: custom:mini-climate
    entity: climate.room
    hide_current_temperature: true
    toggle:
      hide: true
    secondary_info:
      hide: false
```

![image](https://user-images.githubusercontent.com/2870104/192589671-c5724a35-1a44-4726-badf-9fa6962210d1.png)

As you can see, the remaining primary text is still aligned to the top. It would be desired to align it center, in line with the icons and temperatures.

This is far beyond my CSS capabilities. Hoping for an CSS expert to jump in! Thanks!!
