### ISSUE TITLE
Border when embedded since 2022.11.0

### ISSUE THREAD

**Issue by julienlarivee** [artem-sedykh/mini-climate-card#106]
When the card is embedded in an entities card, there is a border around the mini climate card.
Before HA 2022.11.0, there was no border.

![image](https://user-images.githubusercontent.com/55027006/205513528-aab0400b-d762-4d9d-9c07-89d9b9228c94.png)
```
type: entities
entities:
  - entity: climate.air_climatise
    group: true
    type: custom:mini-climate
  - entity: timer.air_climatise
    type: custom:flipdown-timer-card
```

If we look at the same entities, but with native HA cards, there is still no border in 2022.11.0
![image](https://user-images.githubusercontent.com/55027006/205513554-4620a4f7-01e5-48c3-879f-a42ca61a052a.png)
```
type: entities
entities:
  - entity: climate.air_climatise
  - entity: timer.air_climatise
```

Also, the time picker card had the same issue, but they fixed it. Here is the link to it if it can help:
https://github.com/GeorgeSG/lovelace-time-picker-card/issues/43
