### ISSUE TITLE
Icon color wont change with state when on

### ISSUE THREAD

**Issue by marc3k18** [artem-sedykh/mini-climate-card#108]
![Screenshot_20221216-230252](https://user-images.githubusercontent.com/97817024/208223043-1767a15a-2cf0-497d-9c32-0b4806cfc81d.png)

```yaml
type: custom:mini-climate
entity: climate.z2m_t_chambre_garcons
name: Chambre Garçons
icon: mdi:radiator
secondary_info: hvac-action
fan_mode:
  hide: 'on'
indicators:
  power_consumption:
    icon: mdi:flash
    unit: W
    round: 1
    source:
      entity: sensor.z2m_t_chambre_garcons_power
hvac_mode:
  hide: 'on'
````
