### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by vasyna** [artem-sedykh/mini-climate-card#116]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/4531827/230286177-3fc7d84b-368c-4985-95b0-b18829e1a835.png">
How can I change this icon?

**Comment by regevbr** [comment]
Please send over your yaml config

**Comment by vasyna** [comment]
> Please send over your yaml config

type: custom:mini-climate
name: Теплый пол
entity: climate.0x50325ffffe0c28a5
icon: mdi:heat-wave
fan_mode:
  hide: 'on'
target_temperature:
  icons:
    up: mdi:chevron-up
    down: mdi:chevron-down
  unit: °C
  min: 16
  max: 31
  step: 0.5
  change_action: >
    (value, entity) => this.call_service('climate', 'set_temperature', {
    entity_id: entity.entity_id, temperature: value })

**Comment by regevbr** [comment]
```yaml
type: custom:mini-climate
name: Теплый пол
entity: climate.bedroom
icon: mdi:heat-wave
fan_mode:
  hide: 'on'
secondary_info:
  icon: 'mdi:light-flood-down'
target_temperature:
  icons:
    up: mdi:chevron-up
    down: mdi:chevron-down
  unit: °C
  min: 16
  max: 31
  step: 0.5
  change_action: >
    (value, entity) => this.call_service('climate', 'set_temperature', {
    entity_id: entity.entity_id, temperature: value })
```
