### ISSUE TITLE
How do I change the state color in the indicators ?

### ISSUE THREAD

**Issue by DaN66O** [artem-sedykh/mini-climate-card#120]
Can I use styles or mapper to change the color of the value in the  indicators or hide state ?

![Screenshot_18](https://user-images.githubusercontent.com/113509164/236615570-93c00c7a-d6f8-43a8-acca-db13e4750274.png)

Actually I wanted to show only the icon without showing the value.
I thought it could be done using
` .state__value { color: 'transparent !important' }`
or
` .state__value {display: none;}`

I have changed the icon and its color, but I do not know how to make the value invisible.
```
    indicators:
      t_sensor:
        icon:
          template: >
            (value) => (value == 'Ext' ? 'mdi:alpha-e-circle-outline' : 'mdi:alpha-i-circle-outline')
          style: > 
            (value) => (value == 'Ext' ? { color:'#4bc241'} : {color:'#b74a9b'} )
```
