### ISSUE TITLE
Force trailing zero for temperature

### ISSUE THREAD

**Issue by noxhirsch** [artem-sedykh/mini-climate-card#13]
Hi, 
it would be nice, if you have set `temperature: round` to 1 or more, that trailing zeros of the actual temperature don't get cut off. The target temperature in comparison has trailing zeros.
This would make the look of a stack of climate cards look more even. At the moment it looks like this:
![image](https://user-images.githubusercontent.com/30938717/84253608-7476f180-ab10-11ea-8d8e-652820e83d95.png)
Better would be:
12.0 / 22.0
12.0 / 23.0
12.0 / 21.2

Thank you very much!

**Comment by artem-sedykh** [comment]
fixed setting for temperature will be added  
For example:
```yaml
- type: custom:mini-climate
  entity: climate.dahatsu
  name: Кондиционер
  temperature:
    fixed: 1
```
