### ISSUE TITLE
How to display a sensor attribute in the indicators?

### ISSUE THREAD

**Issue by roldengarm** [artem-sedykh/mini-climate-card#131]
I would like to display the last_updated property of a sensor under the indicators. As this is an attribute, I'm not sure how to do that? As the examples only show how to display entities. 
So e.g. the templated value would be: `sensor.living_temp_sensor_temperature.last_updated`

**Comment by regevbr** [comment]
Indicators allow setting the attribute of an entity it is listed in the config table (no examples though) can you share what will be the thoeritcal configuration you want to use so I can direct you better?

**Comment by roldengarm** [comment]
Thanks @regevbr 
So I've got a sensor with id "living_temp_sensor_temperature" which shows the temperature.
I would like to show when it was last updated. This is useful as they are Zigbee wireless sensors and sometimes they no longer update.

When I display it in an entity row card it shows like this, so I'd like to add the "x minutes ago" to mini-climate-card

![image](https://github.com/artem-sedykh/mini-climate-card/assets/37638588/e96e2c31-8fe4-4d37-8160-46bfd2cd2e62)

the YAML for above:
```
entity: sensor.living_room_temp_sensor_temperature
type: custom:multiple-entity-row
name: Living Room
secondary_info: last-changed
entities:
  - entity: sensor.living_room_temp_sensor_humidity
    name: humidity
  - entity: sensor.living_room_temp_sensor_battery
    name: battery
```
Does this answer your question? I really appreciate your support!

**Comment by regevbr** [comment]
Can you share your mini climate card config?

**Comment by roldengarm** [comment]
Sure! @regevbr 

```
type: custom:mini-climate
entity: climate.living_ac
secondary_info:
  type: hvac-action
  hide: false
icon: mdi:heating-coil
indicators:
  battery:
    icon: mdi:battery
    unit: '%'
    round: 1
    source:
      entity: sensor.living_room_temp_sensor_battery
  humidity:
    icon: mdi:water
    unit: '%'
    round: 1
    source:
      entity: sensor.living_room_temp_sensor_humidity
```

**Comment by regevbr** [comment]
```yaml
type: custom:mini-climate
entity: climate.living_ac
secondary_info:
  type: hvac-action
  hide: false
icon: mdi:heating-coil
indicators:
  battery:
    icon: mdi:battery
    unit: '%'
    round: 1
    source:
      entity: sensor.living_room_temp_sensor_battery
  humidity:
    icon: mdi:water
    unit: '%'
    round: 1
    source:
      entity: sensor.living_room_temp_sensor_humidity
  updated:
    source:
      entity: sensor.living_room_temp_sensor_temperature
      attribute: last_updated
```
