### ISSUE TITLE
hvac-mode translation

### ISSUE THREAD

**Issue by derlbear** [artem-sedykh/mini-climate-card#133]
I use
secondary_info:
  type: hvac-mode
which also works. However, the output text is not translated. How can I set it so that the text appears in another language?
![Screenshot 2023-08-13 131749](https://github.com/artem-sedykh/mini-climate-card/assets/60046437/09d02a93-4ce7-4143-b5f2-4ddd17f53ad3)
The default climate card shows the translated output.
![Screenshot 2023-08-13 131818](https://github.com/artem-sedykh/mini-climate-card/assets/60046437/5f3c5926-b924-4c59-9049-3895899b1d2e)

**Comment by regevbr** [comment]
No idea, it is probably a new feature of HA. A PR is welcome if you want to get it working

**Comment by KrX3D** [comment]
you mean the "cool" text`?

![image](https://github.com/artem-sedykh/mini-climate-card/assets/18599852/36c87210-f168-4b94-8a26-0d8c119f4c6b)

for me it worked like this:

```
hvac_mode:
  style: '(value, entity) => ({ color: value !== ''off'' ? ''red !important'' : ''grey'' })'
  source:
    'off':
      icon: mdi:power
      name: Aus
    heat:
      name: Heizen
      icon: mdi:fire
```
