### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by schel4ok** [artem-sedykh/mini-climate-card#134]
I copied js file to **\home-assistant\config\www\community\mini-climate-card\mini-climate-card-bundle.js**
Then I add reference to that file in the same way as I done it for the other extensions, but I don't see mini-climate-card available in HA.

```
lovelace:
  mode: yaml
    - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /local/community/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /local/community/lovelace-weather-card-chart/weather-card-chart.js
      type: module
    - url: /local/community/mini-climate-card/mini-climate-card-bundle.js?v=2.21
      type: module
```
