### ISSUE TITLE
Card not showing in Chrome Version 120.0.6099.71 (Official Build) (x86_64)

### ISSUE THREAD

**Issue by elgeniskogen** [artem-sedykh/mini-climate-card#137]
The card was working fine earlier, now it does not show in Chrome browser on latest OS version for Mac. Shows in HA app on Mac and in Safari in Mac.

Using v2.6.2 of mini-climate-card
Using Version 120.0.6099.71 (Official Build) (x86_64) of Chrome browser
Using these verions of HA:
  Core 2023.12.1
  Supervisor 2023.11.6
  Operating System 11.2
  Frontend 20231208.2

Hope you can help!

br Erik :-)

**Comment by regevbr** [comment]
I have the same chorme version and it works for me on Ubuntu. Sadly don't have a Mac to test it out... If you can provide more info from the dev tools or what ver you can think of I might be able to help but I won't keep my hopes up.
In any case a PR is more than welcome if you are able to fix it yourself.

**Comment by regevbr** [comment]
It does help, let me look into it

**Comment by regevbr** [comment]
@elgeniskogen I just published a new veriosn 2.7.0 that updates the libs that the error came from, hoping it will help... Please let me know if it worked

**Comment by flipaz** [comment]
I'm seeing similar issue on my environment after upgrading to HA 2023.12.1, on arm64 (raspeberry pi 4)
Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

Also tested with latest 2.7.0 and climate cards still do not appear (even after HA restart and browser caches emptied and hard reload)

On chrome dev console, I see the following errors:

![image](https://github.com/artem-sedykh/mini-climate-card/assets/11011874/48fe6df6-8802-4019-80cb-92406b7d2f36)

**Comment by regevbr** [comment]
Sadly I can't help much as it doesn't reproduce on my end and as you can see the obufscated code is impossible to debug by screenshots (it is also very very hard to debug even if I would have managed to reproduce). Once someone comes across that with the skills to debug, I will be happy to assist

**Comment by DaN66O** [comment]
After the update, the card stopped being displayed in chrome 12.0.0.6099.71
Everything worked before the update :(

**Comment by mgiako** [comment]
Hi, I've the same problem on windows 10 and the latest chrome (120.0.6099.130)
Works fine on edge (120.0.2210.91) and on the iphone app.

Here's the log from console

I'm available for testing...

```
4mini-climate-card-bundle.js:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at pc.u (mini-climate-card-bundle.js:1:17388)
    at S.g (mini-climate-card-bundle.js:1:19063)
    at S._$AI (mini-climate-card-bundle.js:1:18608)
    at wc (mini-climate-card-bundle.js:1:22117)
    at He.update (mini-climate-card-bundle.js:1:22506)
    at He.performUpdate (mini-climate-card-bundle.js:1:13447)
    at He.scheduleUpdate (mini-climate-card-bundle.js:1:13111)
    at mini-climate-card-bundle.js:1:13016
    at Generator.next (<anonymous>)
    at h (mini-climate-card-bundle.js:1:1205)
4temp:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at pc.u (mini-climate-card-bundle.js:1:17388)
    at S.g (mini-climate-card-bundle.js:1:19063)
    at S._$AI (mini-climate-card-bundle.js:1:18608)
    at wc (mini-climate-card-bundle.js:1:22117)
    at He.update (mini-climate-card-bundle.js:1:22506)
    at He.performUpdate (mini-climate-card-bundle.js:1:13447)
    at He.scheduleUpdate (mini-climate-card-bundle.js:1:13111)
    at mini-climate-card-bundle.js:1:13016
    at Generator.throw (<anonymous>)
    at h (mini-climate-card-bundle.js:1:1205)
100mini-climate-card-bundle.js:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at pc.u (mini-climate-card-bundle.js:1:17388)
    at S.g (mini-climate-card-bundle.js:1:19063)
    at S._$AI (mini-climate-card-bundle.js:1:18608)
    at wc (mini-climate-card-bundle.js:1:22117)
    at He.update (mini-climate-card-bundle.js:1:22506)
    at He.performUpdate (mini-climate-card-bundle.js:1:13447)
    at He.scheduleUpdate (mini-climate-card-bundle.js:1:13111)
    at mini-climate-card-bundle.js:1:13016
    at Generator.throw (<anonymous>)
    at h (mini-climate-card-bundle.js:1:1205)
4mini-climate-card-bundle.js:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at pc.u (mini-climate-card-bundle.js:1:17388)
    at S.g (mini-climate-card-bundle.js:1:19063)
    at S._$AI (mini-climate-card-bundle.js:1:18608)
    at wc (mini-climate-card-bundle.js:1:22117)
    at He.update (mini-climate-card-bundle.js:1:22506)
    at He.performUpdate (mini-climate-card-bundle.js:1:13447)
    at He.scheduleUpdate (mini-climate-card-bundle.js:1:13111)
    at mini-climate-card-bundle.js:1:13016
    at Generator.throw (<anonymous>)
    at h (mini-climate-card-bundle.js:1:1205)
(anonymous) @ mini-climate-card-bundle.js:1
h @ mini-climate-card-bundle.js:1
g @ mini-climate-card-bundle.js:1
Promise.then (async)
h @ mini-climate-card-bundle.js:1
f @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
_$Ej @ mini-climate-card-bundle.js:1
requestUpdate @ mini-climate-card-bundle.js:1
set @ mini-climate-card-bundle.js:1
set hass @ mini-climate-card-bundle.js:1
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
set hass @ stack-in-card.js:200
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
(anonymous) @ hui-view.ts:153
value @ hui-view.ts:151
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hui-root.ts:607
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:101
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:95
(anonymous) @ connection-mixin.ts:227
s @ store.js:19
(anonymous) @ entities.js:74
e.subscribeMessage.type @ entities.js:76
(anonymous) @ connection.js:23
_handleMessage @ connection.js:15
Show 5 more frames
Show less
156mini-climate-card-bundle.js:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at pc.u (mini-climate-card-bundle.js:1:17388)
    at S.g (mini-climate-card-bundle.js:1:19063)
    at S._$AI (mini-climate-card-bundle.js:1:18608)
    at wc (mini-climate-card-bundle.js:1:22117)
    at He.update (mini-climate-card-bundle.js:1:22506)
    at He.performUpdate (mini-climate-card-bundle.js:1:13447)
    at He.scheduleUpdate (mini-climate-card-bundle.js:1:13111)
    at mini-climate-card-bundle.js:1:13016
    at Generator.throw (<anonymous>)
    at h (mini-climate-card-bundle.js:1:1205)
u @ mini-climate-card-bundle.js:1
g @ mini-climate-card-bundle.js:1
_$AI @ mini-climate-card-bundle.js:1
wc @ mini-climate-card-bundle.js:1
update @ mini-climate-card-bundle.js:1
performUpdate @ mini-climate-card-bundle.js:1
scheduleUpdate @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
h @ mini-climate-card-bundle.js:1
g @ mini-climate-card-bundle.js:1
Promise.then (async)
h @ mini-climate-card-bundle.js:1
f @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
_$Ej @ mini-climate-card-bundle.js:1
requestUpdate @ mini-climate-card-bundle.js:1
set @ mini-climate-card-bundle.js:1
set hass @ mini-climate-card-bundle.js:1
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
set hass @ stack-in-card.js:200
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
(anonymous) @ hui-view.ts:153
value @ hui-view.ts:151
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hui-root.ts:607
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:101
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:95
(anonymous) @ connection-mixin.ts:227
s @ store.js:19
(anonymous) @ entities.js:74
e.subscribeMessage.type @ entities.js:76
(anonymous) @ connection.js:23
_handleMessage @ connection.js:15
Show 5 more frames
Show less
previsioni.php:156 
        
781mini-climate-card-bundle.js:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at pc.u (mini-climate-card-bundle.js:1:17388)
    at S.g (mini-climate-card-bundle.js:1:19063)
    at S._$AI (mini-climate-card-bundle.js:1:18608)
    at wc (mini-climate-card-bundle.js:1:22117)
    at He.update (mini-climate-card-bundle.js:1:22506)
    at He.performUpdate (mini-climate-card-bundle.js:1:13447)
    at He.scheduleUpdate (mini-climate-card-bundle.js:1:13111)
    at mini-climate-card-bundle.js:1:13016
    at Generator.throw (<anonymous>)
    at h (mini-climate-card-bundle.js:1:1205)
```

**Comment by regevbr** [comment]
Can you please share your card config?

**Comment by mgiako** [comment]
sure...
I've four of them:

```
          - type: custom:stack-in-card
            mode: vertical
            cards:
              - type: custom:mini-climate
                entity: climate.termosala
                name: Sala
                group: true
                secondary_info:
                  type: hvac-action
                  source:
                    heating:
                      icon: 'mdi:fire'
                      name: 'Riscaldamento'
    
                icon: mdi:fire
                fan_mode:
                  disabled: true
                  hide: true
                toggle:
                  hide: true
                indicators:
                  humidity:
                    icon: mdi:water
                    unit: '%'
                    round: 1
                    source:
                      entity: sensor.ble_sala_humidity
                  wifi:
                    icon: mdi:wifi
                    unit: ''
                    source:
                      entity: sensor.termodisplay_wifi_signal
                buttons:
                  screen:
                    type: button              
                    location: main
                    icon: mdi:television-ambient-light
                    state:
                      entity: switch.termodisplay_backlight

    
              - type: custom:mini-climate
                entity: climate.termosopra
                name: Camere
                group: true
                secondary_info:
                  type: hvac-action
                  source:
                    heating:
                      icon: 'mdi:fire'
                      name: 'Riscaldamento'
    
                icon: mdi:fire
                fan_mode:
                  disabled: true
                  hide: true
                toggle:
                  hide: true
                indicators:
                  humidity:
                    icon: mdi:water
                    unit: '%'
                    round: 1
                    source:
                      entity: sensor.ble_camera_humidity
                  wifi:
                    icon: mdi:wifi
                    unit: ''
                    source:
                      entity: sensor.termosopra_signal
    
                buttons:
                  screen:
                    type: button              
                    location: main
                    icon: mdi:television-ambient-light
                    state:
                      entity: switch.termosopra_display
    
              - type: custom:mini-climate
                entity: climate.climacamera
                name: Clima Camera
                group: true
                secondary_info:
                  type: hvac-action
                  source:
                    heating:
                      icon: 'mdi:fire'
                      name: 'Riscaldamento'
                    cooling:
                      icon: 'mdi:snowflake'
                      name: 'Raffreddamento'
    
                toggle:
                  hide: true
                indicators:
                  humidity:
                    icon: mdi:water
                    unit: '%'
                    round: 1
                    source:
                      entity: sensor.ble_camera_humidity
    
                  wifi:
                    icon: mdi:wifi
                    unit: ''
                    source:
                      entity: sensor.climacamera_wifi_signal

                      
                
              - type: custom:mini-climate
                entity: climate.climamarghe    
                name: Clima Marghe
                group: true
                secondary_info:
                  type: hvac-action
                  source:
                    heating:
                      icon: 'mdi:fire'
                      name: 'Riscaldamento'
                    cooling:
                      icon: 'mdi:snowflake'
                      name: 'Raffreddamento'
                toggle:
                  hide: true            
                indicators:
                  humidity:
                    icon: mdi:water
                    unit: '%'
                    round: 1
                    source:
                      entity: sensor.ble_cameretta_humidity
                  wifi:
                    icon: mdi:wifi
                    #unit: 'dBm'
                    source:
                      entity: sensor.climamarghe_wifi_signal
```

**Comment by regevbr** [comment]
Can you please try to create a simple card (not stack) with just 1 mini climate card that reproduces the issue? If you can check if one of the 4 is not creating thee issue this will make this task a whole lot easier

**Comment by mgiako** [comment]
Here:

```
          - type: custom:mini-climate
            entity: climate.termosala
            name: Sala
```

```
56mini-climate-card-bundle.js:1 Uncaught (in promise) TypeError: (intermediate value)(intermediate value)(intermediate value).importNode is not a function
    at ed.u (mini-climate-card-bundle.js:1:21785)
    at fd.g (mini-climate-card-bundle.js:1:23553)
    at fd._$AI (mini-climate-card-bundle.js:1:23086)
    at md (mini-climate-card-bundle.js:1:26659)
    at Xj.update (mini-climate-card-bundle.js:1:27046)
    at Xj.performUpdate (mini-climate-card-bundle.js:1:17939)
    at Xj.scheduleUpdate (mini-climate-card-bundle.js:1:17369)
    at mini-climate-card-bundle.js:1:17274
    at Generator.throw (<anonymous>)
    at t (mini-climate-card-bundle.js:1:1205)
u @ mini-climate-card-bundle.js:1
g @ mini-climate-card-bundle.js:1
_$AI @ mini-climate-card-bundle.js:1
md @ mini-climate-card-bundle.js:1
update @ mini-climate-card-bundle.js:1
performUpdate @ mini-climate-card-bundle.js:1
scheduleUpdate @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
t @ mini-climate-card-bundle.js:1
g @ mini-climate-card-bundle.js:1
Promise.then (async)
t @ mini-climate-card-bundle.js:1
f @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
(anonymous) @ mini-climate-card-bundle.js:1
_$EP @ mini-climate-card-bundle.js:1
requestUpdate @ mini-climate-card-bundle.js:1
set @ mini-climate-card-bundle.js:1
set hass @ mini-climate-card-bundle.js:1
(anonymous) @ hui-view.ts:153
value @ hui-view.ts:151
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hui-root.ts:607
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:101
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:95
(anonymous) @ connection-mixin.ts:227
s @ store.js:19
(anonymous) @ entities.js:74
e.subscribeMessage.type @ entities.js:76
(anonymous) @ connection.js:23
_handleMessage @ connection.js:15
```

**Comment by mgiako** [comment]
even the simplest card gives the error on chrome, on safari or edge it is ok

**Comment by regevbr** [comment]
I managed to create the non-minified code of the card so we can see a real stack trace and potentially do a proper breakpoint.
Please delete the file /config/www/community/mini-climate-card/mini-climate-card-bundle.js.gz
Please set the content of the file /config/www/community/mini-climate-card/mini-climate-card-bundle.js.gz to 
https://gist.github.com/regevbr/047092e6f76fb2777a4ed8f4fe698bb8
Go to http://<ha url>/config/lovelace/resources and change a single digit in the query string number of the mini climate card 
![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/7fbe145c-cbec-49df-be8d-23a0f54d368f)
Open your HA in a new window, and open the insepct window and make sure that the disable cache is checked in the network tab
![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/d4433c86-a5d1-4fe1-8ff6-753001a5969a)
Then reload and send the stack trace. If you can put breakpoints and see what element it tries to call the importNode and gather more information it will be great

**Comment by mgiako** [comment]
Sorry for the delay... we had Christmas lunch.

I have two questions on your instructions.

1) I deleted the .gz file and set the content of the .js file to https://gist.github.com/regevbr/047092e6f76fb2777a4ed8f4fe698bb8. Right? Not in the the .gz file (you wrote in the gz.file)

2) I'm in yaml mode... how can I follow your instructions if I can't open the resources page?

Sorry I'm not so good at this...

**Comment by regevbr** [comment]
1. correct my bad
2. what do you mean yaml mode? this is a fronend URL not configuration file. You can go to it by going to the settings page, clicking on dashboards. clicking the 3 dots menu at the top, and choosing resources

**Comment by mgiako** [comment]
1) ok!

2) in configuration.yaml I have:

```
lovelace:
  mode: yaml
```
so if I use the 3 dots menu/resources I get: " You are using your dashboard in YAML mode, therefore you cannot manage your resources through the UI. Manage them in configuration.yaml."

In configuration.yaml I have:


 ```
 resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/lovelace-plotly-graph-card/plotly-graph-card.js
      type: module      
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module      
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/history-explorer-card/history-explorer-card.js  
      type: module
    - url: /hacsfiles/lovelace-fan-xiaomi/xiaomi-fan-card.js
      type: module
    - url: /hacsfiles/hass-swipe-navigation/swipe-navigation.js
      type: module      
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/ha-sankey-chart/ha-sankey-chart.js
      type: module
    - url: /hacsfiles/formulaone-card/formulaone-card.js
      type: module  
    - url: /hacsfiles/mini-climate-card/mini-climate-card-bundle.js
      type: module      
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
```
