### ISSUE TITLE
Button Color change not working in themes

### ISSUE THREAD

**Issue by naimadfpv** [artem-sedykh/mini-climate-card#142]
I would like to change the button color in my theme but its not working. i tried to set icon & button color to white in my_theme.yaml

`my_theme:
  mini-climate-icon-color: "#FFFFFF"
  mini-climate-button-color: '#FFFFFF'

`

The first one (icon-color) is working as expected but the second does not. It doesn´t change color to white. It stays default as yellow

**Comment by regevbr** [comment]
screenshot please so I can be sure on what icon you are referring to

**Comment by naimadfpv** [comment]
![image](https://github.com/artem-sedykh/mini-climate-card/assets/39771894/33788edc-64fa-4342-b0b7-f5c9654f708a)

**Comment by regevbr** [comment]
yellow is the default value for active buttons. You need to change state-binary_sensor-active-color

**Comment by naimadfpv** [comment]
in that same file?

```
theme:
  mini-climate-icon-color: "#FFFFFF"
  mini-climate-button-color: "#FFFFFF"
  state-binary-sensor-active-color: "#FFFFFF"
```

**Comment by regevbr** [comment]
Think so never tried it before

**Comment by naimadfpv** [comment]
is it possible to change the upper left icon as well?

**Comment by regevbr** [comment]
It works great, you need to call the frontend them reload service to see the changes

**Comment by regevbr** [comment]
![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/66b7297a-daa4-42f7-a1b6-29c7efddabc7)

**Comment by naimadfpv** [comment]
ok thx. i will try that

**Comment by regevbr** [comment]
It should affect the upper icon as well

**Comment by naimadfpv** [comment]
i restarted homeassistant but it didnt change color.

what do you exactly mean with call frontend and restart service?

**Comment by regevbr** [comment]
![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/d09722af-3b5f-4639-875d-142058dbc902)

**Comment by naimadfpv** [comment]
it doenst work.

i did a service restart. 
restarted homeassistant. 
cleared browser cache.
no error in yaml.... idk

**Comment by regevbr** [comment]
No idea, you will have to use the debug console to understand where the color comes from on the HTML element

**Comment by regevbr** [comment]
Just another guess - seems you have dark mode enabled. maybe you need to do something like the following:
```

frontend:
  themes:
    default2:
      ha-card-border-width: 0px
      ha-card-border-radius: 0px
      modes:
        dark:
          ha-card-border-width: 1px
          ha-card-border-radius: 0px
```
