### ISSUE TITLE
how to remove three dots

### ISSUE THREAD

**Issue by a1ex-ak** [artem-sedykh/mini-climate-card#143]
Please forgive me for my ignorance, but I haven’t found how to remove the three dots at the bottom of the map?
Thanks for the help.

![Снимок экрана от 2024-02-04 19-56-05](https://github.com/artem-sedykh/mini-climate-card/assets/121604147/a7a12e55-1343-4564-a1fb-d9b3d58de733)

**Comment by a1ex-ak** [comment]
fan_mode:
      hide: true

**Comment by regevbr** [comment]
```yaml
type: custom:mini-climate
entity: climate.living_room
toggle:
  hide: true
````
