### ISSUE TITLE
how to change the icon

### ISSUE THREAD

**Issue by a1ex-ak** [artem-sedykh/mini-climate-card#144]
I'm trying to change the secondary_info icon

```yaml
secondary_info: 
      type: hvac-mode
      icon: 'mdi:thermostat'
```

![Снимок экрана от 2024-02-05 13-11-20](https://github.com/artem-sedykh/mini-climate-card/assets/121604147/7175ffc4-29d4-42c5-8b50-9a09db7d6578)

but it doesn't change, what am I doing wrong?

**Comment by regevbr** [comment]
no idea, works for me:

![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/82f7c223-bf51-4be8-93b4-ee5009e37fd9)

**Comment by regevbr** [comment]
Please always paste full yaml config, not pictures

**Comment by a1ex-ak** [comment]
> без понятия, у меня работает:
> 
> ![изображение](https://private-user-images.githubusercontent.com/5775519/302253599-82f7c223-bf51-4be8-93b4-ee5009e37fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjg1NTksIm5iZiI6MTcwNzEyODI1OSwicGF0aCI6Ii81Nzc1NTE5LzMwMjI1MzU5OS04MmY3YzIyMy1iZjUxLTRiZTgtOTNiNC1lZTUwMDllMzdmZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMTAxNzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQ5NDQ2MGU0ZTk4NjhiMjI1NzY2YzAzNTE5NTI1Zjk1M2U0YTQwOTZlNGIzOGU4ZDNkNWE2ZmUwMjlkOTQ3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p1zl48s0QHJTBVyfbCAkPEJi0jOpmFvVw-hJEswYNmg)

```yaml
type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: climate.kitchen_chalet
    type: custom:mini-climate
    name: 'Кухня '
    icon: mdi:countertop
    swap_temperatures: true
    group: true
    secondary_info: 
      type: hvac-mode
      icon: 'mdi:thermostat'
    toggle:
      hide: true
    hvac_mode:
      style: >-
        (value, entity) => ({ color: value !== 'off' ? 'orange !important' :
        'grey' })
      source:
        heat:
          icon: mdi:fire
          name: 'Обогрев '
        'off':
          icon: mdi:power
          name: 'Выкл. '
      change_action: >
        (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
        entity_id: entity.entity_id, hvac_mode: selected })
    indicators:
      humidity:
        icon:
          template: () => 'mdi:water-percent'
          style: |
            (value) => (value > 0 ? { color: '#4682B4'} : {})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_humidity
      power_consumption:
        icon:
          template: >
            (value) => (value > 90 ? 'mdi:battery' : {}),(value) => (value < 60
            ? 'mdi:battery-50' : 'mdi:battery'),(value) => (value < 80 ?
            'mdi:battery-70' : 'mdi:battery')
          style: >
            (value) => (value > 90 ? { color: '#008000'} : {}),(value) => (value
            < 60 ? { color: '#FF0000'} : { color: '#008000'}),(value) => (value
            < 80 ? { color: '#FFFF00'} : { color: '#008000'})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_battery
  - type: divider
  - entity: switch.sonoff_1001676f3c
    icon: mdi:radiator
    secondary_info: last-changed
```

**Comment by regevbr** [comment]
hvac_mode not hvac-mode please pay attention

**Comment by a1ex-ak** [comment]
> ```yaml
> secondary_info: 
>       type: hvac-mode
>       icon: 'mdi:thermostat'
> ```

Corrected it, but now it only displays the icon and no text

```yaml
secondary_info: 
      type: hvac_mode
      icon: 'mdi:thermostat'
    toggle:
      hide: true
```

**Comment by regevbr** [comment]
no idea, works for me:

![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/af9c72b7-0c41-4969-87ef-b878736d6514)

**Comment by regevbr** [comment]
Im sorry I got it all wrong.... It should be hvac-mode. But in hvac-mode it will not use the provided icon as it doesn't really make sense - the icon need to change according to the HVAC mode.
In order to overide icons (and the text shown) you need o map all possible hvac modes in the `hvac_mode` source attribute.
For example:
```yaml
type: custom:mini-climate
entity: climate.living_room
secondary_info:
  type: hvac-mode
hvac_mode:
  source:
    'off':
      name: bla
      icon: mdi:thermostat
```
![image](https://github.com/artem-sedykh/mini-climate-card/assets/5775519/ca16bfc6-b54b-4d21-b464-a66512607589)

Also please notice that the rendering of the component while you edit the config is not stable (not sure why) so to verify changes, please save it and see what happens

**Comment by a1ex-ak** [comment]
> ```yaml
> secondary_info:
>   type: hvac-mode
> hvac_mode:
>   source:
>     'off':
>       name: bla
>       icon: mdi:thermostat
> ```

```yaml
type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: climate.kitchen_chalet
    type: custom:mini-climate
    name: 'Кухня '
    icon: mdi:countertop
    swap_temperatures: true
    group: true
    secondary_info: hvac-mode
    secondary_info:
      type: hvac-mode
    hvac_mode:
      source:
        'off':
          name: bla
          icon: mdi:thermostat
        heat:
          name: Обогрев
          icon: mdi:thermostat
    toggle:
      hide: true
    hvac_mode:
      style: >-
        (value, entity) => ({ color: value !== 'off' ? 'orange !important' :
        'grey' })
      source:
        heat:
          icon: mdi:fire
          name: 'Обогрев '
        'off':
          icon: mdi:power
          name: 'Выкл. '
      change_action: >
        (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
        entity_id: entity.entity_id, hvac_mode: selected })
    indicators:
      humidity:
        icon:
          template: () => 'mdi:water-percent'
          style: |
            (value) => (value > 0 ? { color: '#4682B4'} : {})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_humidity
      power_consumption:
        icon:
          template: >
            (value) => (value > 90 ? 'mdi:battery' : {}),(value) => (value < 60
            ? 'mdi:battery-50' : 'mdi:battery'),(value) => (value < 80 ?
            'mdi:battery-70' : 'mdi:battery')
          style: >
            (value) => (value > 90 ? { color: '#008000'} : {}),(value) => (value
            < 60 ? { color: '#FF0000'} : { color: '#008000'}),(value) => (value
            < 80 ? { color: '#FFFF00'} : { color: '#008000'})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_battery
  - type: divider
  - entity: switch.sonoff_1001676f3c
    icon: mdi:radiator
    secondary_info: last-changed
```

errror
```yaml
Обнаружены ошибки конфигурации:
duplicated mapping key (12:5)

  9 |     swap_temperatures: true
 10 |     group: true
 11 |     secondary_info: hvac-mode
 12 |     secondary_info:
----------^
 13 |       type: hvac-mode
 14 |     hvac_mode:
```

**Comment by regevbr** [comment]
so act according to what the message says - remove the duplicate key

**Comment by a1ex-ak** [comment]
> поэтому действуйте согласно сообщению - удалите дубликат переключателя

I don’t quite understand how to do this, since the duplicate hvac_mode is a button in front of the temperature numbers

![Снимок экрана от 2024-02-05 14-19-55](https://github.com/artem-sedykh/mini-climate-card/assets/121604147/55e05d6c-cb6f-432c-95bb-a1de293e3958)

**Comment by regevbr** [comment]
it is talking about the yaml syntax, not related to the card itself. You can have a yaml that have duplicate keys:
```yaml
a: 1
a: 1
```

**Comment by a1ex-ak** [comment]
> речь идет о синтаксисе yaml, не имеющем отношения к самой карте. У вас может быть yaml с повторяющимися ключами:
> 
> ```yaml
> a: 1
> a: 1
> ```

Please forgive me, but I'm even more confused

**Comment by regevbr** [comment]
Just past the full config here that gives you that error

**Comment by regevbr** [comment]
I had a typo in the last comment I fixed it

**Comment by a1ex-ak** [comment]
> Just past the full config here that gives you that error

I'm sorry, but I don't understand. Pok your nose, what am I doing wrong?

**Comment by regevbr** [comment]
Please past the full config here so I can check

**Comment by regevbr** [comment]
*paste

**Comment by a1ex-ak** [comment]
```yaml
type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: climate.kitchen_chalet
    type: custom:mini-climate
    name: 'Кухня '
    icon: mdi:countertop
    swap_temperatures: true
    group: true
    secondary_info:
      type: hvac-mode
      hvac_mode:
        source:
          'off':
            name: bla
            icon: mdi:thermostat
          heat:
            name: Обогрев
            icon: mdi:thermostat
    toggle:
      hide: true
    hvac_mode:
      style: >-
        (value, entity) => ({ color: value !== 'off' ? 'orange !important' :
        'grey' })
      source:
        heat:
          icon: mdi:fire
          name: 'Обогрев '
        'off':
          icon: mdi:power
          name: 'Выкл. '
      change_action: >
        (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
        entity_id: entity.entity_id, hvac_mode: selected })
    indicators:
      humidity:
        icon:
          template: () => 'mdi:water-percent'
          style: |
            (value) => (value > 0 ? { color: '#4682B4'} : {})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_humidity
      power_consumption:
        icon:
          template: >
            (value) => (value > 90 ? 'mdi:battery' : {}),(value) => (value < 60
            ? 'mdi:battery-50' : 'mdi:battery'),(value) => (value < 80 ?
            'mdi:battery-70' : 'mdi:battery')
          style: >
            (value) => (value > 90 ? { color: '#008000'} : {}),(value) => (value
            < 60 ? { color: '#FF0000'} : { color: '#008000'}),(value) => (value
            < 80 ? { color: '#FFFF00'} : { color: '#008000'})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_battery
  - type: divider
  - entity: switch.sonoff_1001676f3c
    icon: mdi:radiator
    secondary_info: last-changed
```

**Comment by regevbr** [comment]
And what is the issue with it?

**Comment by a1ex-ak** [comment]
> И в чем проблема?

![Снимок экрана от 2024-02-05 14-33-28](https://github.com/artem-sedykh/mini-climate-card/assets/121604147/dd9428a2-a24e-4a89-8182-0cecaad8d308)

 mdi:fire instead of mdi:thermostat

**Comment by regevbr** [comment]
According to docs, hvac_mode is not inside the secondary info object, but outside of it, you already have it fix it there please

**Comment by a1ex-ak** [comment]
> According to docs, hvac_mode is not inside the secondary info object, but outside of it, you already have it fix it there please

So this is exactly what I can’t figure out how to do?

**Comment by regevbr** [comment]
```yaml
type: entities
show_header_toggle: false
state_color: true
entities:
  - entity: climate.living_room
    type: custom:mini-climate
    name: 'Кухня '
    icon: mdi:countertop
    swap_temperatures: true
    group: true
    secondary_info:
      type: hvac-mode
    toggle:
      hide: true
    hvac_mode:
      style: >-
        (value, entity) => ({ color: value !== 'off' ? 'orange !important' :
        'grey' })
      source:
        'off':
          name: bla
          icon: mdi:thermostat
        heat:
          name: Обогрев
          icon: mdi:thermostat
      change_action: >
        (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
        entity_id: entity.entity_id, hvac_mode: selected })
    indicators:
      humidity:
        icon:
          template: () => 'mdi:water-percent'
          style: |
            (value) => (value > 0 ? { color: '#4682B4'} : {})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_humidity
      power_consumption:
        icon:
          template: >
            (value) => (value > 90 ? 'mdi:battery' : {}),(value) => (value < 60
            ? 'mdi:battery-50' : 'mdi:battery'),(value) => (value < 80 ?
            'mdi:battery-70' : 'mdi:battery')
          style: >
            (value) => (value > 90 ? { color: '#008000'} : {}),(value) => (value
            < 60 ? { color: '#FF0000'} : { color: '#008000'}),(value) => (value
            < 80 ? { color: '#FFFF00'} : { color: '#008000'})
        unit: '%'
        round: 1
        source:
          entity: sensor.sonoff_a480072e16_battery
  - type: divider
  - entity: switch.sonoff_1001676f3c
    icon: mdi:radiator
    secondary_info: last-changed
```

You already have hvac_mode set in your coniofg , just use it instead
