### ISSUE TITLE
how to change the icon #144

### ISSUE THREAD

**Issue by a1ex-ak** [artem-sedykh/mini-climate-card#145]
> ```yaml
> secondary_info: 
>       type: hvac-mode
>       icon: 'mdi:thermostat'
> ```

Corrected it, but now it only displays the icon and no text

```yaml
secondary_info: 
      type: hvac_mode
      icon: 'mdi:thermostat'
    toggle:
      hide: true
```

![Снимок экрана от 2024-02-05 13-27-05](https://github.com/artem-sedykh/mini-climate-card/assets/121604147/fe4e2c3b-1864-49f3-8491-1f3392b06ade)
