### ISSUE TITLE
Ability to disable hvac_mode and fan_mode icons

### ISSUE THREAD

**Issue by divanikus** [artem-sedykh/mini-climate-card#15]
Since now we can have buttons on the main view, it would be cool to be able to disable hvac_mode and fan_mode icons completelly. I mean just hide them.

Or maybe I'm missing something?
![image](https://user-images.githubusercontent.com/3438036/84265898-4a332d00-ab2c-11ea-93c3-7084cb975d20.png)

My current setup is the following:
```
buttons:
  auto:
    icon: 'mdi:cached'
    location: main
    state:
      mapper: 'state => (state == ''heat_cool'' ? ''on'': ''off'')'
    toggle_action: >
      (state, entity, climate_entity) => this.call_service('climate',
      'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode:
      'heat_cool' })
  cool:
    icon: 'mdi:snowflake'
    location: main
    state:
      mapper: 'state => (state == ''cool'' ? ''on'': ''off'')'
    toggle_action: >
      (state, entity, climate_entity) => this.call_service('climate',
      'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode: 'cool'
      })
  dry:
    icon: 'mdi:water-percent'
    location: main
    state:
      mapper: 'state => (state == ''dry'' ? ''on'': ''off'')'
    toggle_action: >
      (state, entity, climate_entity) => this.call_service('climate',
      'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode: 'dry'
      })
  fan:
    icon: 'mdi:fan'
    location: main
    state:
      mapper: 'state => (state == ''fan_only'' ? ''on'': ''off'')'
    toggle_action: >
      (state, entity, climate_entity) => this.call_service('climate',
      'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode:
      'fan_only' })
  heat:
    icon: 'mdi:fire'
    location: main
    state:
      mapper: 'state => (state == ''heat'' ? ''on'': ''off'')'
    toggle_action: >
      (state, entity, climate_entity) => this.call_service('climate',
      'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode: 'heat'
      })
  power:
    icon: 'mdi:power'
    location: main
    toggle_action: "(\tstate, entity, climate_entity) => this.call_service('climate', 'set_hvac_mode', { entity_id: climate_entity.entity_id, hvac_mode: 'off' })\n"
entity: climate.konditsioner
secondary_info:
  type: fan-mode-dropdown
hvac_mode:
  change_action: >
    (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
    entity_id: entity.entity_id, hvac_mode: selected })
  source:
    cool:
      icon: 'mdi:snowflake'
      name: Охлаждение
    dry:
      icon: 'mdi:water-percent'
      name: Осушение
    fan_only:
      icon: 'mdi:fan'
      name: Вентиляция
    heat:
      icon: 'mdi:fire'
      name: Обогрев
    heat_cool:
      icon: 'mdi:cached'
      name: Авто
    'off':
      icon: 'mdi:power'
      name: Выкл
type: 'custom:mini-climate'
```
