### ISSUE TITLE
Hide target_temperature and adjusting buttons when climate entity off

### ISSUE THREAD

**Issue by bas89** [artem-sedykh/mini-climate-card#150]
Is there any way to hide the target temperature, current temperature and the buttons to increase / decrease the target temperatue, when the climate entity is just plain off? This would look so much cleaner. Using `hide_current_temperature`, I only see a way to hide the current temperature.

**Comment by regevbr** [comment]
There is none currently. A PR is more than welcome

**Comment by artem-sedykh** [comment]
Not doing this.

Hiding the setpoint and the chevrons while the unit is off would reflow the card on every on/off: the control row shrinks, the name grows, the mode menu jumps. That is the opposite of what the layout is built to do. `hide_icon: true` is static, so nothing jumps. This request is not.

The chevrons are the control, not clutter. That the unit is on is already visible: the mode, `hvac_action`, the icon, the highlights. Setting a temperature while the unit is off and turning it on afterwards is a normal gesture, and hiding the setpoint would take it away.

The current temperature can already hide on a condition, including `off`:

```yaml
type: custom:mini-climate
entity: climate.your_climate
hide_current_temperature: >
  (value, entity, target_entity, climate_entity) => climate_entity.state === 'off'
```

Docs: https://artem-sedykh.github.io/mini-climate-card/controls/#temperature

That is as far as this goes. Please reopen if something about the chevrons is actually broken. Hiding them when the unit is off is not on the table.
