### ISSUE TITLE
Target temperature display configuration

### ISSUE THREAD

**Issue by chrisbennight** [artem-sedykh/mini-climate-card#155]
I have an ecobee thermostat paired via homekit, and haven't been able to figure out how to get the target temperature to display properly.  

Here is how it looks:
![IMG_0167](https://github.com/user-attachments/assets/de235c7d-59b4-47c4-8a36-1817d3dc6ad0)

Where the "-"  character is I'm trying to get the current target temp displayed.
My thermostat has  target_temp_high and target_temp_low attributes, which I think are different attributes than what the card looks for by default.

Ideally, based on the current state (heating/cooling), the correct target temperature would be displayed in the mini-climate card.  I haven't been able to parse through the docs and understand how to do that.

(and yeah, units (C/F) are wrong, but saw the other issue on fixing that)

Card YAML
```
type: custom:mini-climate
entity: climate.my_ecobee
icon: mdi:air-conditioner
hide_current_temperature: false
temperature:
  target_entity: climate.my_ecobee
target_temperature:
  source: climate.my_ecobee
swap_temperatures: true
secondary_info:
  type: hvac-action
indicators:
  humidity:
    icon: mdi:water
    unit: '%'
    round: 1
    source:
      entity: sensor.living_room_humidity
  power_consumption:
    icon: mdi:flash
    unit: W
    round: 1
    source:
      entity: sensor.a_c_15_1min                  
```

here are the attributes on the climate object (from developer tools->states)
```
hvac_modes:
  - "off"
  - heat
  - cool
  - heat_cool
min_temp: 45
max_temp: 92
min_humidity: 20
max_humidity: 50
fan_modes:
  - "on"
  - auto
current_temperature: 72
temperature: null
target_temp_high: 71
target_temp_low: 64
current_humidity: 53
humidity: 36
fan_mode: auto
hvac_action: cooling
friendly_name: My ecobee
supported_features: 399
```

Really appreciate the integration, and thanks for the work around it!

**Comment by regevbr** [comment]
```yaml
target_temperature:
  source:
    attribute: target_temp_high
```
Currently, there is no way to specify it dynamically. A PR is more than welcome
