### ISSUE TITLE
Hide a button on hvac_mode state condition

### ISSUE THREAD

**Issue by Icar128** [artem-sedykh/mini-climate-card#157]
Hello,
First of all, it is a great card, loving it! Thank you for the job.
I successfully setup the card using hvac_mode and some buttons but I'm wondering if I can hide a specific button based on hvac_mode state. I would like to hide the button called ''verrou'' when hvac_mode is off.
I've tried this but unsuccessfully. Any idea?
Thanks!

```
buttons:
  verrou:
    icon: mdi:lock
    state:
      entity: switch.radian_salon_verrouillage
    hide: >
      (hvac_mode, attribute) => hvac_mode === 'off'

```

**Comment by regevbr** [comment]
hvac_mode in the function you supplied is the state of the entity you supplied `switch.radian_salon_verrouillage`
You can access the climate entity by using the third argument
```
      (_, __, climate_entity) => climate_entity.attributes.hvac_mode === 'off'
```

**Comment by regevbr** [comment]
Or the 4th argument, as listed in the docs:

![image](https://github.com/user-attachments/assets/a71b95a4-a312-42db-a235-89aca8829958)

**Comment by Icar128** [comment]
Thank you very much for your quick answer but I'm a bit confused. This button is not a climate entity.
The entity switch.radian_salon_verrouillage has no hvac_mode as it is only a switch (on/off).
Is it be possible to hide this switch button based on the hvac_mode of the entity climate.radian_salon (when hvac_mode = off)?

**Comment by regevbr** [comment]
just like I wrote or
```
 (_, __, ___, hvac_mode) => hvac_mode === 'off'
```

**Comment by Icar128** [comment]
I tried both but no effect. The button verrou (icon: lock) is not hidden.

hvac_mode = off
![image](https://github.com/user-attachments/assets/158abcca-3804-4376-b227-046fad2f9a89)

hvac_mode = heat
![image](https://github.com/user-attachments/assets/5aad8e37-9482-488a-a724-53d0185dfe1f)


Maybe the full yaml config will help:

```yaml
type: custom:mini-climate
entity: climate.radian_salon
name: Radian Salon
icon: mdi:fire
style: '(value, entity) => ({ color: value !== ''off''? ''green !important'' : ''white''})'
secondary_info:
  type: hvac-mode
fan_mode:
  hide: true
hvac_mode:
  style: >-
    (value, entity) => ({ color: value !== 'off'? 'orangelight !important' :
    'white'})
  source:
    'off':
      icon: mdi:power
      name: Arrêt
    heat:
      icon: mdi:fire
      name: Marche
  change_action: >
    (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
    entity_id: entity.entity_id, hvac_mode: selected })
buttons:
  preset_mode:
    type: dropdown
    location: main
    style: >-
      (state) => (state == 'Automatique' ? {color:'green !important'} :
      {color:'white'})
    source:
      Automatique:
        name: Automatique
        icon: mdi:auto-mode
      Manuel:
        name: Manuel
        icon: mdi:hand-back-left
    change_action: |
      (selected, state, entity) => this.call_service('climate',
       'set_preset_mode', { entity_id: entity.entity_id, preset_mode: selected })
  Auto:
    icon: mdi:auto-mode
    location: bottom
    active: entity => entity.state == 'Automatique'
    state:
      mapper: |
        (state) => state === 'Automatique' ? 'on' : 'off'
    style: >-
      (state) => (state == 'Automatique' ? {color:'green !important'} :
      {color:'white'})
    toggle_action: >
      (state, entity) => this.call_service('climate', 'set_preset_mode', {
      entity_id: entity.entity_id, preset_mode: 'Automatique' })
  Manuel:
    icon: mdi:hand-back-left
    location: bottom
    style: >-
      (state, entity) => ({ color: state === 'Manuel' ? 'red !important' :
      'white' })
    state:
      mapper: |
        (state) => state === 'Manuel' ? 'on' : 'off'
    toggle_action: >
      (state, entity) => this.call_service('climate', 'set_preset_mode', {
      entity_id: entity.entity_id, preset_mode: 'Manuel' })
  freeze:
    icon: mdi:snowflake
    state:
      entity: switch.radian_salon_hors_gel
  verrou:
    icon: mdi:lock
    state:
      entity: switch.radian_salon_verrouillage
    hide: |
      (_, __, ___, hvac_mode) => hvac_mode === 'off'
indicators:
  freeze:
    icon: mdi:snowflake
    source:
      entity: switch.radian_salon_hors_gel
  verrou:
    icon: mdi:lock
    active: (state, entity) => entity.state !== 'off'
    source:
      entity: switch.radian_salon_verrouillage
``` 
I'm sorry to bother you but I guess I've missed something!

**Comment by regevbr** [comment]
I think you need to use `hide: >` and not `hide: |`

**Comment by Icar128** [comment]
Same issue using >
I wrote > in the whole config but they've been replaced by | when saved!

**Comment by regevbr** [comment]
seems there is an issue, you can see the values by using console log.
This should work:
```
    (_, __, climate_entity) => climate_entity.state === 'off'
```

**Comment by Icar128** [comment]
Great! Works with (_, __, climate_entity) => climate_entity.state === 'off'
But all > are still replaced by |

```yaml
type: custom:mini-climate
entity: climate.radian_salon
name: Radian Salon
icon: mdi:fire
style: '(value, entity) => ({ color: value !== ''off''? ''green !important'' : ''white''})'
secondary_info:
  type: hvac-mode
fan_mode:
  hide: true
hvac_mode:
  style: >-
    (value, entity) => ({ color: value !== 'off'? 'orangelight !important' :
    'white'})
  source:
    'off':
      icon: mdi:power
      name: Arrêt
    heat:
      icon: mdi:fire
      name: Marche
  change_action: >
    (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
    entity_id: entity.entity_id, hvac_mode: selected })
buttons:
  preset_mode:
    type: dropdown
    location: main
    style: >-
      (state) => (state == 'Automatique' ? {color:'green !important'} :
      {color:'white'})
    source:
      Automatique:
        name: Automatique
        icon: mdi:auto-mode
      Manuel:
        name: Manuel
        icon: mdi:hand-back-left
    change_action: |
      (selected, state, entity) => this.call_service('climate',
       'set_preset_mode', { entity_id: entity.entity_id, preset_mode: selected })
  Auto:
    icon: mdi:auto-mode
    location: bottom
    active: entity => entity.state == 'Automatique'
    state:
      mapper: |
        (state) => state === 'Automatique' ? 'on' : 'off'
    style: >-
      (state) => (state == 'Automatique' ? {color:'green !important'} :
      {color:'white'})
    toggle_action: >
      (state, entity) => this.call_service('climate', 'set_preset_mode', {
      entity_id: entity.entity_id, preset_mode: 'Automatique' })
  Manuel:
    icon: mdi:hand-back-left
    location: bottom
    style: >-
      (state, entity) => ({ color: state === 'Manuel' ? 'red !important' :
      'white' })
    state:
      mapper: |
        (state) => state === 'Manuel' ? 'on' : 'off'
    toggle_action: >
      (state, entity) => this.call_service('climate', 'set_preset_mode', {
      entity_id: entity.entity_id, preset_mode: 'Manuel' })
  freeze:
    icon: mdi:snowflake
    state:
      entity: switch.radian_salon_hors_gel
  verrou:
    icon: mdi:lock
    state:
      entity: switch.radian_salon_verrouillage
    hide: |
      (_, __, climate_entity) => climate_entity.state === 'off'
indicators:
  freeze:
    icon: mdi:snowflake
    source:
      entity: switch.radian_salon_hors_gel
  verrou:
    icon: mdi:lock
    active: (state, entity) => entity.state !== 'off'
    source:
      entity: switch.radian_salon_verrouillage

``` 

Thanks a lot for your help.
