### ISSUE TITLE
indicators: - Change icon based on state

### ISSUE THREAD

**Issue by pieri70** [artem-sedykh/mini-climate-card#158]
Hello
I'm a yaml inexpert
I am using this mini card and I would like to change the icon of a window sensor (binary) based on its state (on/off)

under indicators I have 

```
indicators:
  window_state:
    source:
      entity: binary_sensor.window_contact
    icon_template:
      {% if is_state("binary_sensor.window_contact", "off") %}
        mdi:window-closed-variant
      {% else %}
        mdi:window-open-variant
      {% endif %}
```

but it don't work and the editor refuse to save this code.
Is there some other way to deal with this?
Thanks
Pietro

**Comment by regevbr** [comment]
this is not a proper yaml, please see example from docs:
```
type: custom:mini-climate
entity: climate.my_ac
indicators:
  humidity:
    icon:
      template: >
        (value) => (value > 30 ? 'mdi:weather-rainy' : 'mdi:water')
    unit: '%'
    round: 1
    source:
      entity: sensor.humidity
```

**Comment by pieri70** [comment]
Thanks
I solved with this code
```
indicators:
  window_state:
    source:
      entity: binary_sensor.window_contact
    icon:
      template: >
        (value) => (value == 'off' ? 'mdi:window-closed-variant' : 'mdi:window-open-variant')
```
Is there some way to cnange both icon and its color?
