### ISSUE TITLE
toggle hvac action not working or not possible?

### ISSUE THREAD

**Issue by Spartacus68** [artem-sedykh/mini-climate-card#160]
I am looking for a function to toggle the state between “heat” (standby) and “off” by clicking the “fire” -icon. But there is only a dropdown. How can I change it to toggle?

![image](https://github.com/user-attachments/assets/66d80cd9-3a0f-424c-9531-a0f790576e42)

```
type: custom:mini-climate
entity: climate.thermostat_gartenhaus
name: Gartenhaus
icon: mdi:greenhouse
toggle:
  default: true
fan_mode:
  hide: true
hvac_mode:
  source:
    "off":
      icon: mdi:power
      name: aus
    heat:
      icon: mdi:fire
      name: heizen
secondary_info:
  type: hvac-action
  source:
    heating: heizen
    idle: standby
    "off": aus
indicators:
  humidity:
    icon: mdi:water
    unit: "%"
    round: 1
    source:
      entity: sensor.gh_ht_in_humidity
  power_consumption:
    icon: mdi:flash
    unit: W
    round: 1
    source:
      entity: sensor.gh_a02_k0_power
buttons:
  preset_mode:
    type: dropdown
    location: main
    state:
      attribute: preset_mode
    source:
      night: Abgesenkt
      day: Heizen
      auto: Automatisch
    icon: mdi:thermometer
```

**Comment by Spartacus68** [comment]
is there nobody who can help? The card is great, but without support I have to switch to annother solution.

**Comment by regevbr** [comment]
not possible currently, PR is welcome. Feel free to use whichever card your heart desires

**Comment by artem-sedykh** [comment]
This is possible today, with no change to the card - sorry it took this long to get a real answer here, and sorry for the earlier "not possible".

The mode control itself is always a dropdown: the card draws `hvac_mode` as a menu whatever `type` says. What you asked for is the other way round - hide that dropdown, and put an ordinary button in the row it stood in. `location: main` is what puts a button in the top row rather than behind the toggle, an `icon` template gives it your two icons, and `toggle_action` reads the mode the entity is in and sends the other one:

```yaml
hvac_mode:
  hide: true
buttons:
  hvac_toggle:
    type: button
    location: main
    order: 0
    icon:
      template: "state => (state === 'off' ? 'mdi:power' : 'mdi:fire')"
    toggle_action: >
      (state, entity) => this.call_service('climate', 'set_hvac_mode', { entity_id: entity.entity_id, hvac_mode: state === 'off' ? 'heat' : 'off' })
```

In your card that is the whole edit: the `hvac_mode.source` block goes, everything else stays as you have it. A button with no `state` of its own reads the climate entity's state, which for a climate entity is the mode, so `off` leaves the button dark and `heat` lights it up without an `active` written for it - and your `secondary_info: hvac-action` keeps saying heizen / standby / aus as before. Nothing here is new, so it works on the version you already have.

It is written down now, with a picture: [A press instead of the mode dropdown](https://artem-sedykh.github.io/mini-climate-card/examples/#a-press-instead-of-the-mode-dropdown).

`location` turned out to have no example anywhere - only a row in the option table - which is a fair part of why this read as impossible. It has one now in [Buttons](https://artem-sedykh.github.io/mini-climate-card/buttons/#location), along with the other move it makes possible: [the fan mode in the top row](https://artem-sedykh.github.io/mini-climate-card/examples/#the-fan-mode-in-the-top-row).

Both recipes are cards on the test bench with scenarios asserting them, so this answer fails a run if it stops being true rather than quietly going stale in a thread.

One trade to be aware of: a button is a press, so it is the right shape for two modes and the wrong one for five. A unit with more modes still wants the dropdown.
