### ISSUE TITLE
How to set indicator style based on hvac_mode

### ISSUE THREAD

**Issue by mauropisoni** [artem-sedykh/mini-climate-card#168]
Hello, 

first, great job with this mini-climate card!!!

I would like to set a style of and indicator based on the HVAC_MODE currently active:

example:
(if it's cooling I would like to have the radiant icon blue, else if it's heating the color should be red.

radiant_indicator:
    icon:
      template: () => 'mdi:heating-coil'
      style: |
        (value,entity) => {
          if (<<?hvac_mode?>> == 'cool') {
            return { color: 'blue' };
          } else return { color: 'red' };
        }
    source:
      entity: binary_sensor.sleeping_room_floor_demand

How can I access to climate.sleeping_room attributes from indicators definition?

thanks!!

**Comment by Henry-Sir** [comment]
My sample with hvac_action:


```
hvac_mode:
  hide: false
  style: >-
    (value, entity) => (entity.attributes.hvac_action == 'idle' ? {
    color: 'grey !important' } : 
      (entity.attributes.hvac_action == 'cooling' ? { color: 'blue !important' } : 
      (entity.attributes.hvac_action == 'heating' ? { color: 'red !important' } : {}
    )))
  source:
    "off":
      icon: mdi:power
      name: Aus
    heat:
      icon: mdi:weather-sunny
      name: Heizen
    auto:
      icon: mdi:cached
      name: Auto
    cool:
      icon: mdi:snowflake
      name: Kühlen
    dry:
      icon: mdi:water
      name: Trocknen
    fan_only:
      icon: mdi:fan
      name: Lüfter
```

<img width="490" height="404" alt="Image" src="https://github.com/user-attachments/assets/53e41740-7069-4a27-937f-8749ab17cf55" />
