### ISSUE TITLE
Humidity indicator source as attribute

### ISSUE THREAD

**Issue by ITensEI** [artem-sedykh/mini-climate-card#20]
My humidity is an attribute of my climate entity. I've currently setup a template sensor for it to show up, but it would be great to just set the source to an attribute of an entity.

**Comment by artem-sedykh** [comment]
If I understand what you need correctly, then here is an example:
```yaml
- type: custom:mini-climate
  entity: climate.daikin
  indicators:
    humidity:
      icon: mdi:water
      unit: '%'
      source:
        attribute: ac_humidity
```
