### ISSUE TITLE
Trouble calling service with button

### ISSUE THREAD

**Issue by elfhack** [artem-sedykh/mini-climate-card#21]
Hi. This is not really a bug, but I'm trying to use a button to toggle a fan device, and keep failing. Maybe you could point me to what I'm doing wrong? When I try to use the power button, I get 
```
WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities fan.xiaomi_air_purifier_pro
 ```

Calling fan.toggle on fan.xiaomi_air_purifier_pro with the entity_id in the debug console works perfectly

```yaml
- entity: fan.xiaomi_air_purifier_pro
    name: Living Room Purifier
    type: 'custom:mini-climate'
    icon: 'mdi:air-purifier'
    hvac_mode:
      hide: true
    buttons:
      power:
        icon: 'mdi:power'
        location: main
        state:
          entity: fan.xiaomi_air_purifier_pro
        toggle_action: >
        (entity) => this.call_service('fan', 'toggle', { entity_id: entity.entity_id })
    temperature:
      unit: AQI
    target_temperature:
      source:
        entity: fan.xiaomi_air_purifier_pro
        attribute: aqi
      icons:
        up: null
        down: null
    secondary_info:
      type: fan-mode-dropdown
    toggle:
      hide: true
    indicators:
      aqi:
        icon: 'mdi:air-filter'
        source:
          entity: fan.xiaomi_air_purifier_pro
          attribute: average_aqi
      humidity:
        icon: 'mdi:water'
        unit: '%'
        source:
          entity: fan.xiaomi_air_purifier_pro
          attribute: humidity
    group: true
```

**Comment by artem-sedykh** [comment]
`toggle_action` arguments: state, entity, climate_entity, hvac_mode see [readme](https://github.com/artem-sedykh/mini-climate-card#buttons)  
Fixed your configuration:
```yaml
- entity: fan.xiaomi_air_purifier_pro
  type: 'custom:mini-climate'
  name: Living Room Purifier
  icon: 'mdi:air-purifier'
  secondary_info: fan-mode-dropdown
  group: true
  hvac_mode:
    hide: true
  buttons:
    power:
      icon: 'mdi:power'
      location: main
      # If the same as the main entity can be omitted
#      state:
#        entity: fan.xiaomi_air_purifier_pro
      # i fixed it
      toggle_action: >
        (state, entity) => this.call_service('fan', 'toggle', { entity_id: entity.entity_id })
  temperature:
    unit: AQI
  target_temperature:
    source:
        # entity: fan.xiaomi_air_purifier_pro
      attribute: aqi
    icons:
      up: null
      down: null
  toggle:
    hide: true
  indicators:
    aqi:
      icon: 'mdi:air-filter'
      source:
#        entity: fan.xiaomi_air_purifier_pro
        attribute: average_aqi
    humidity:
      icon: 'mdi:water'
      unit: '%'
      source:
        # entity: fan.xiaomi_air_purifier_pro
        attribute: humidity
```
