### ISSUE TITLE
Determine active state of button

### ISSUE THREAD

**Issue by elfhack** [artem-sedykh/mini-climate-card#26]
Sorry, one more question. I am baffled as to how and even if I can set a button to to be active or not. Consider the following

```yaml
  - buttons:
      auto:
        icon: 'mdi:alpha-a-circle-outline'
        state:
          attribute: speed
        toggle_action: >
          (state,entity) => this.call_service('fan','set_speed', { entity_id:
          entity.entity_id, speed: 'Auto'})
      silent:
        icon: 'mdi:weather-night'
        state:
          attribute: speed
        toggle_action: >
          (state,entity) => this.call_service('fan','set_speed', { entity_id:
          entity.entity_id, speed: 'Silent'})
      favorite:
        icon: 'mdi:heart-outline'
        state:
          attribute: speed
        toggle_action: >
          (state,entity) => this.call_service('fan','set_speed', { entity_id:
          entity.entity_id, speed: 'Favorite'})
      power:
        icon: 'mdi:power'
        location: main
        toggle_action: >
          (state, entity) => this.call_service('fan', 'toggle', { entity_id:
          entity.entity_id })
```
What I'm trying to do here is to have buttons for different modes in addition to a power on/off switch in the main area. However, I can't figure out for the life of me how to make those mode buttons light up or not if their respective mode is selected in the 'speed' attribute. While I'm operating here on the xiaomi fan example, I'm trying to do exactly the same on my samsung hvac as well. I think i'm supposed to be using active: in some way, but can't figure out the incantation for that.

**Comment by artem-sedykh** [comment]
the button must be state on/off  use the `mapper` function  
```yaml
  - buttons:
      auto:
        icon: 'mdi:alpha-a-circle-outline'
        state:
          attribute: speed
          mapper: "(state, entity) => state.toLowerCase() === 'auto' ? 'on': 'off'"
        toggle_action: >
          (state,entity) => this.call_service('fan','set_speed', { entity_id:
          entity.entity_id, speed: 'Auto'})
      silent:
        icon: 'mdi:weather-night'
        state:
          attribute: speed
          mapper: "(state, entity) => state.toLowerCase() === 'silent' ? 'on': 'off'"
        toggle_action: >
          (state,entity) => this.call_service('fan','set_speed', { entity_id:
          entity.entity_id, speed: 'Silent'})
      favorite:
        icon: 'mdi:heart-outline'
        state:
          attribute: speed
          mapper: "(state, entity) => state.toLowerCase() === 'favorite' ? 'on': 'off'"
        toggle_action: >
          (state,entity) => this.call_service('fan','set_speed', { entity_id:
          entity.entity_id, speed: 'Favorite'})
      power:
        icon: 'mdi:power'
        location: main
        toggle_action: >
          (state, entity) => this.call_service('fan', 'toggle', { entity_id:
          entity.entity_id })
```
