### ISSUE TITLE
List ordering

### ISSUE THREAD

**Issue by elfhack** [artem-sedykh/mini-climate-card#27]
On restart, home assistant rewrites lovelace yaml in alphabetical order. So for example

```yaml
source:
        Schedule:
          icon: 'mdi:calendar'
          name: Schedule
        Frost Guard:
          icon: 'mdi:snowflake-alert'
          name: Frost Guard
```

Becomes this on hass reboot
```yaml
source:
        Frost Guard:
          icon: 'mdi:snowflake-alert'
          name: Frost Guard
        Schedule:
          icon: 'mdi:calendar'
          name: Schedule
```
Buttons have an order option, could lists support this as well?
