### ISSUE TITLE
Card won't display °F

### ISSUE THREAD

**Issue by julianrinaldi** [artem-sedykh/mini-climate-card#3]
I've installed this and changed the units, but it still displays °C on the card in lovelace:

`- entity: climate.thermostat
    temperature:
      round: 1
      unit: °F
    target_temperature:
      unit: °F
    type: 'custom:mini-climate'`

Do I have an error somewhere? Do I need to change another setting?

**Comment by artem-sedykh** [comment]
Fixed in version 1.0.3

```yaml
- type: custom:mini-climate
  entity: climate.dahatsu
  temperature:
    unit: 'F'
```
In previous version  
```yaml
- type: custom:mini-climate
  entity: climate.dahatsu
  current_temperature:
    unit: 'F'
```
