### ISSUE TITLE
Ability to hide icon, name, fanspeed

### ISSUE THREAD

**Issue by matejdro** [artem-sedykh/mini-climate-card#40]
I would like to have a minimal card with only temperature and up/down buttons.

Is there a way to hide those entries?

![image](https://user-images.githubusercontent.com/507922/107870521-5b8dbf80-6e99-11eb-82ff-fc88c96d475c.png)

Preferably, card would even collapse when those are hidden, so it would only encompass the size of the temperature area.

**Comment by matejdro** [comment]
This is the closest I've gotten:

```
type: 'custom:mini-climate'
entity: climate.my_climate
hvac_mode:
  hide: 'on'
icon: blank
name: ' '
toggle:
  hide: 'on'
fan_mode:
  hide: 'on'
secondary_info:
  type: hvac-action
  name: ''
  icon: ''
```
