### ISSUE TITLE
Add ability to show thermostat preset mode

### ISSUE THREAD

**Issue by dpositive** [artem-sedykh/mini-climate-card#41]
I would like to see the current preset and change it, but I don’t know how to get the preset information.

**Comment by btsimonh** [comment]
+1
just starting to get my head around using the card, but preset is not mentioned anywhere here.
p.s. also just discovered 'decluttering-card.js' - which is excellent as you can create a template for mini-climate, and then easily replicate for each (in my case radiator with TRV).

**Comment by btsimonh** [comment]
@dpositive - I have it working...

[withpresetmode.txt](https://github.com/artem-sedykh/mini-climate-card/files/6054145/withpresetmode.txt)

ok, so I have 'hijacked' fan_mode, hardcoded MY set of preset mode values, and used the climate service to set it on selection.
Using fan_mode means that you can easily put the dropdown in 'secondary info'.

But also, see a similar 'button' dropdown.  For me, this is less nice because you have to access it through the three dots expander..  but if you actually have 'fan_mode' in your heating/cooling system, then it may be a good option rather than hijacking fan_mode as preset_mode.

br,

Simon

**Comment by rklueber** [comment]
you can use buttons
````
buttons:
  preset_mode:
    type: dropdown
    location: main
    icon: 'mdi:thermometer'
    state:
      attribute: preset_mode
    active: state => state == 'comfort'
    source:
      eco: Fenster auf
      sleep: Schlafen
      away: Abwesend
      comfort: Komfort
    change_action: >
      (selected, state, entity) => this.call_service('climate',
      'set_preset_mode', { entity_id: entity.entity_id, preset_mode: selected })

````

**Comment by kwithus** [comment]
Hi, I generally like the idea to use a button for the preset mode. However I would like to see the selected profile (name) on the card. I tried to show it somehow as an indicator. But I have no idea how I can define the attribute as an source for that.
Anyone any idea?

**Comment by kwithus** [comment]
First of all thanks for the prompt reply. However, I am still quite a newbie, copy/paste works pretty good for me, but mostly I don’t have a real understanding  of the code.
Therefore, could you give me a; example?I really don’t know what format of code / lines I have to use.
I do have the entity (climate.badunten_hk8_2) the attribute is ‚preset-mode‘, how do I get this as source for the indicator and can specify naming for the different states of the preset-modes (day,night,auto)
Would be great if you could help me out. Thanks

**Comment by regevbr** [comment]
```yml
      indicators:
        preset_mode:
          icon: 'mdi:approximately-equal'
          source:
            attribute: preset_mode
```

I strongly suggest to learn the yml files structure and syntax
