### ISSUE TITLE
Templating the Entity Icon

### ISSUE THREAD

**Issue by rklueber** [artem-sedykh/mini-climate-card#42]
Hello,

before I create an issue, please do let me know that this card is one of the most powerful cards I have seen. The intelligence in there is very powerful and avoids using a lot of automations which would be required otherwise. Well done!

I am not clear if it is possible to template the entity Icon. My climate entities use only preset_mode. Depending on preset_mode I would like to use different Icons for the entity.

I understand this is not possible for now. Let me know if this can be done. Otherwise consider this as a feature request.

Yours sincerely.
Ralf

**Comment by KrX3D** [comment]
i also would like that, and also to be able to change the icon color:

`
type: custom:mini-climate
entity: climate.better_thermostat_az
name: ' '
icon: mdi:radiator
`

like for indicators:

`
    icon:
      template: () => 'mdi:thermometer-low'
      style: |
        () =>  ({ color: '#00bb33'})
`

![image](https://github.com/artem-sedykh/mini-climate-card/assets/18599852/744f96e5-ba29-4fb3-9169-a6c5c7b49785)

**Comment by artem-sedykh** [comment]
This is now on `master`, and your case - "my climate entities use only `preset_mode`, and I want a different icon per preset" - is what the object form of `icon` is for:

```yaml
type: custom:mini-climate
entity: climate.thermostat
icon:
  items:
    comfort: mdi:sun-thermometer
    eco: mdi:leaf
    away: mdi:home-export-outline
    boost: mdi:fire
  template: "(entity) => this.items[entity.attributes.preset_mode] || 'mdi:thermostat'"
```

`items` is not a card option - it is your own data. Any extra key on the `icon` object is readable from the template as `this.<key>`, which is the same extension point a button icon already uses. So the glyph list stays in YAML and the template is one line.

I ran exactly the block above before posting it: `comfort` / `eco` / `away` / `boost` each give their glyph, and a preset that is not in the list - including `none`, and a thermostat with no `preset_mode` attribute at all - falls back to `mdi:thermostat`. That fallback matters more than it looks: without the `||` a missing preset would put `undefined` on the icon.

Note there is no `style` in that example, deliberately. Without it the icon keeps being tinted by whether the unit is on, which is probably what you want when the preset chooses the glyph. Add `style` and it takes the colour over completely:

```yaml
icon:
  items: { comfort: mdi:sun-thermometer, eco: mdi:leaf }
  template: "(entity) => this.items[entity.attributes.preset_mode] || 'mdi:thermostat'"
  style: >
    (entity) => ({
      color: entity.attributes.preset_mode === 'eco'
        ? 'var(--mc-icon-color)'
        : 'var(--mc-icon-active-color)',
    })
```

`template` and `style` both receive `(climate_entity, hvac_mode)`. Documentation: [icon](https://artem-sedykh.github.io/mini-climate-card/configuration/#icon).

**Not in a release yet.** It lands in **v3.3.0**, which has not been published - `master` carries it now. When v3.3.0 is out, HACS will offer it; there is nothing to install today.

Thank you for the report, and for how precisely it was written - "I understand this is not possible for now, otherwise consider this a feature request" was accurate, and the request was the right one.
