### ISSUE TITLE
Feature request: last-updated in addition to last-changed

### ISSUE THREAD

**Issue by gryzli133** [artem-sedykh/mini-climate-card#59]
It would be nice to see if there is communication with the AC/Thermostats. With last-updated I would see if there is data exchange all the time. The best would it be to even get that in the bottom line, like this:

![image](https://user-images.githubusercontent.com/30415928/144867361-e1b0b9c4-c093-4b14-b861-e2469cd4d65d.png)

I had problem with some thermostats and did not saw it, so my house was a bit colder today. No big issue, but maybe I would see that when there would be indication for communication fault/lost. Even last changed would not really help, but last update should help, because normally there is refresh every 60s.

Thank you in advance!

```
type: custom:mini-climate
entity: climate.mp_smartthermostat_112_1
target_temperature:
  step: 0.5
temperature:
  round: 0
indicators:
  temperature:
    icon: mdi:thermometer
    unit: °C
    round: 2
    tap_action: more-info
    source:
      entity: sensor.mp_smartthermostat_112_10
  humidity:
    icon: mdi:water
    unit: '%'
    round: 1
    tap_action: more-info
    source:
      entity: sensor.mp_smartthermostat_112_11
  pressure:
    icon: mdi:gauge
    unit: hPa
    round: 1
    tap_action: more-info
    source:
      entity: sensor.mp_smartthermostat_112_12
```
