### ISSUE TITLE
add more characters to the name

### ISSUE THREAD

**Issue by conrad66** [artem-sedykh/mini-climate-card#6]
Возможно ли добавить больше символов для имени кондиционера ?
![Screenshot_16](https://user-images.githubusercontent.com/5843698/83914987-0c748400-a77b-11ea-824c-fc39ea80382c.png)

**Comment by artem-sedykh** [comment]
Привет! Конечно завтра выкачу новый релиз с этой доработкой

**Comment by conrad66** [comment]
Отлично !, Спасибо. Еще бы возможность увеличить шрифт немного

**Comment by artem-sedykh** [comment]
есть настройка `scale`
```yaml
- type: custom:mini-climate
  entity: climate.dahatsu
  name: Кондиционер
  scale: 1.1
```
