### ISSUE TITLE
Feature request: last-updated in addition to last-changed

### ISSUE THREAD

**Issue by moostmartijn** [artem-sedykh/mini-climate-card#63]
I would like to see the following option available:

```
- type: custom:mini-climate
  entity: climate.nest
  name: Nest thermostaat
  icon: mdi:fire           
  secondary_info:
    type: last-updated
```

<img width="387" alt="Schermafbeelding 2022-01-15 om 17 54 06" src="https://user-images.githubusercontent.com/31592734/149630422-ebb37c35-6817-4277-8f4f-5d966a2ab6a3.png">

With `last-changed` (Laatst gewijzigd: 1 uur geleden) it shows the last time the temperature changed. 
I would want it to show the last time the entity was updates (Laatst bijgewerkt: 8 minuten geleden)

Thanks in advance.
