### ISSUE TITLE
Option to hide indicator value and show only icon

### ISSUE THREAD

**Issue by zarebski-m** [artem-sedykh/mini-climate-card#64]
I would like to create an indicator that displays only icon, without the value. This makes sense for binary sensors. In my case I'd like a window indicator that changes the icon, without state value displayed:

```yaml
indicators:
  window:
    source:
      entity: binary_sensor.bedroom_windows
    icon:
      template: |
        (value) => value === 'off' 
          ? 'mdi:window-closed' 
          : 'mdi:window-open'
      style: |
        (value) => value === 'off' 
          ? {} 
          : { color: 'blue' }
```

This works fine but it still displays sensor value next to the icon (`on` or `off`). I would like to hide the value completely and have just the icon indicator.

![image](https://user-images.githubusercontent.com/1415942/150352309-09753483-b351-4d26-a525-12e69223c19a.png)
![image](https://user-images.githubusercontent.com/1415942/150352576-db5e0044-5de2-4981-8716-e71e883bc1b5.png)

**Comment by jesseklm** [comment]
Solved with https://github.com/artem-sedykh/mini-climate-card/pull/121.

Yours would look like this:
```yaml
indicators:
  window:
    source:
      entity: binary_sensor.bedroom_windows
    icon:
      template: |
        (value) => value === 'off' 
          ? 'mdi:window-closed' 
          : 'mdi:window-open'
      style: |
        (value) => value === 'off' 
          ? {} 
          : { color: 'blue' }
    value:
      style: |
        () => ({display: 'none'})
```
