### ISSUE TITLE
current selection in selected_value list is not bold

### ISSUE THREAD

**Issue by kannkann** [artem-sedykh/mini-climate-card#72]
previously the current value was marked in bold in the selected_value list. that was quite useful.
could that be restored? I use 4 buttons with lists in my card.
Thank you for the great work.

ps.: could there be more examples? how do filters work?
I have an attribute as following, but I am not sure how to populate the selection list automatically.
```
fan_modes:
  - auto
  - '1'
....
```

**Comment by regevbr** [comment]
Sure I already have a fix, will release it shortly.
Can you please explain more in detail what it is you want to achieve?

**Comment by regevbr** [comment]
released in [v2.0.2](https://github.com/artem-sedykh/mini-climate-card/releases/tag/v2.0.2)

**Comment by kannkann** [comment]
Thank you, it works.

Regarding the filter:
Currently I use 4 buttons for fan speed, left-right swing mode, top-button swing mode, and climate mode. I was wondering if there is a way to populate the selection list using the climate attribute with an array of options.
Current setting I am using:
```
  swing_mode:
    type: dropdown
    state:
      attribute: swing_mode
    source:
      '2':
        name: '2'
        order: 2
      '3':
        name: '3'
        order: 3
      '4':
        name: '4'
        order: 4
      auto:
        name: auto
        order: 0
      1_up:
        name: 1_up
        order: 1
      5_down:
        name: 5_down
        order: 5
      swing:
        name: swing
        order: 6
    change_action: >
      (selected, state, climate_entity) => this.call_service('climate',
      'set_swing_mode', { entity_id: climate_entity.entity_id, swing_mode:
      selected })
```

I was wondering if something like this works somehow?
```
swing_mode:
    type: dropdown
    state:
      attribute: swing_mode
    source:
      __filter: >
          """I do not understand this part."""
    change_action: >
      (selected, state, climate_entity) => this.call_service('climate',
      'set_swing_mode', { entity_id: climate_entity.entity_id, swing_mode:
      selected })
```
