### ISSUE TITLE
Invisible when casting

### ISSUE THREAD

**Issue by TomaszDom** [artem-sedykh/mini-climate-card#80]
Mini climate card is invisible when the view is cast, at least to my Google Nest Hub 2nd Gen. All other cards show up correctly.

```
      - type: custom:mini-climate
        entity: climate.lazienka_grzejnik
        target_temperature:
          step: 0.5
        secondary_info: hvac-mode
        indicators:
          valve:
            icon: mdi:valve
            unit: '%'
            round: 1
            source:
              entity: sensor.lazienka_grzejnik_position
          preset_mode:
            icon: mdi:car-cruise-control
            source:
              attribute: preset_mode
        icon: mdi:radiator
        fan_mode:
          hide: 'on'
          active: false
          icon: mdi:none
          disabled: true
        buttons:
          preset_mode:
            type: dropdown
            location: main
            icon: mdi:thermometer
            state:
              attribute: preset_mode
            active: state => state !== 'none'
            source:
              eco: Eco
              comfort: Comfort
              boost: Boost
              manual: Manual
            change_action: >
              (selected, state, entity) => this.call_service('climate',
              'set_preset_mode', { entity_id: entity.entity_id, preset_mode:
              selected })
      - type: custom:mini-climate
        entity: climate.salon
        target_temperature:
          step: 0.5
        secondary_info: hvac-mode
        indicators:
          valve_left:
            icon: mdi:valve
            unit: '%'
            round: 1
            source:
              entity: sensor.salon_lewy_position
          valve_right:
            icon: mdi:valve
            unit: '%'
            round: 1
            source:
              entity: sensor.salon_prawy_position
          preset_mode:
            icon: mdi:car-cruise-control
            source:
              attribute: preset_mode
        icon: mdi:radiator
        fan_mode:
          hide: 'on'
          active: false
          icon: mdi:none
          disabled: true
        buttons:
          preset_mode:
            type: dropdown
            location: main
            icon: mdi:thermometer
            state:
              attribute: preset_mode
            active: state => state !== 'none'
            source:
              eco: Eco
              comfort: Comfort
              boost: Boost
              manual: Manual
            change_action: >
              (selected, state, entity) => this.call_service('climate',
              'set_preset_mode', { entity_id: entity.entity_id, preset_mode:
              selected })
      - type: custom:mini-climate
        entity: climate.sypialnia
        target_temperature:
          step: 0.5
        secondary_info: hvac-mode
        indicators:
          valve_left:
            icon: mdi:valve
            unit: '%'
            round: 1
            source:
              entity: sensor.sypialnia_lewy_position
          valve_right:
            icon: mdi:valve
            unit: '%'
            round: 1
            source:
              entity: sensor.sypialnia_prawy_position
          preset_mode:
            icon: mdi:car-cruise-control
            source:
              attribute: preset_mode
        icon: mdi:radiator
        fan_mode:
          hide: 'on'
          active: false
          icon: mdi:none
          disabled: true
        buttons:
          preset_mode:
            type: dropdown
            location: main
            icon: mdi:thermometer
            state:
              attribute: preset_mode
            active: state => state !== 'none'
            source:
              eco: Eco
              comfort: Comfort
              boost: Boost
              manual: Manual
            change_action: >
              (selected, state, entity) => this.call_service('climate',
              'set_preset_mode', { entity_id: entity.entity_id, preset_mode:
              selected })
```

![20220503_114919](https://user-images.githubusercontent.com/9348532/166434781-d131ca75-58fd-4b48-8b78-1764bf054bae.png)

![screenshot](https://user-images.githubusercontent.com/9348532/166434803-31fc1cf3-a29b-433f-ac67-980f0a5556c3.PNG)

I'm running Home Assistant 2022.4.7 with mini-climate-card v2.1.1.
