### ISSUE TITLE
Quick query on adding a custom colour to the HVAC icon for heat and cool modes.

### ISSUE THREAD

**Issue by mishnz** [artem-sedykh/mini-climate-card#84]
Thanks for approving the push the other day.
I was about to look at adding code to allow colour changes on the HVAC icon for different states, but I get the feeling its already there.

Can you provide an example of how I'd add "red" for heat and "blue" for cool in the example below:
```
            heat:
              icon: mdi:thermometer-chevron-up
              name: Heat
            cool:
              icon: mdi:thermometer-chevron-down
              name: Cool
```
I've tried various approaches, but I think I'm missing a trick.
