### ISSUE TITLE
Indicator Mapper for Icon an Source

### ISSUE THREAD

**Issue by Olum-hack** [artem-sedykh/mini-climate-card#91]
Hello,
I have a problem with the mapper of an indicator:
```
tur:
  icon:
    template: >
      (value) => (value === 'Zu' ? 'mdi:door-closed' : 'mdi:door-open')
  source: 
    values:
      'on': 'Offen'
      'off': 'Zu'
    entity: binary_sensor.eg_luftung_kuchentur
    mapper: value => this.source.values[value]
  tap_action: more-info
```

I have to put the mapped values in the template of the icon. Is that correct?
Or should the value of the icon separate to the value of the source?
