### ISSUE TITLE
Hide secondary_info option

### ISSUE THREAD

**Issue by ThomDietrich** [artem-sedykh/mini-climate-card#95]
Hello,

Contrary to other elements (like `toggle` or `hvac_mode`) we can't hide the secondary info. Could you add that feature? If it's already possible, the README does not clearly show that.

```yaml
secondary_info:
      hide: true
```

Thanks and cheers!

**Comment by regevbr** [comment]
released in v2.3.0

**Comment by ThomDietrich** [comment]
You my friend are amazing! 😃

**Comment by ThomDietrich** [comment]
One issue remains :( The remaining text isn't centered correctly, neither is the left icon looking at it.

![image](https://user-images.githubusercontent.com/2870104/192589671-c5724a35-1a44-4726-badf-9fa6962210d1.png)

**Comment by regevbr** [comment]
CSS sadly is not in my wheelhouse :-( A PR will be more than welcome...

**Comment by ThomDietrich** [comment]
Mine neither. I won't be able to help here much.

This change seems to fix the icon misalignment:
```css
.ctl-wrap {
  margin-top: auto;
}
```
Please try and merge if it also works for you.

----

This change seems to fix the text misalignment:
```css
.entity__info__name_wrap {
  display: flex;
  justify-content: center;
}
.entity__info__name {
  margin-bottom: auto;
  margin-top: auto;
}
```

But only for me. As soon as I try to add the secondary_info back it's a mess.
